### PR TITLE
Resolved failing tests

### PR DESCRIPTION
**Pull request by jennylia**
This Pull Request is addressed to:
#19 

Some of the tests were assuming res.body is not an empty object. The response we are interested in for the client is actually in res.text.
I moved some of the unit tests to a new test suite.
The npm test command now passes:

Server running at http://Jennys-MacBook-Air.local:3000/
  Testing express server
    ✓ Responds to /
    ✓ Returns 404 for everything else
    ✓ Returns empty array for api/status (438ms)
    ✓ Returns empty array if no service added (142ms)
    ✓ Returns 404 if posting service without serviceName
    ✓ Returns 404 if posting service without value
    ✓ Returns true service when deleting it by id (53ms)
    ✓ Returns 404 if deleting service without id (54ms)

  Testing HTML response
    ✓ Checking HTML responses (43ms)

  9 passing (810ms)

### CODE REVIEW

**Comment by jennylia** [comment]
@BondAnthony Is there someway I can run the coverage testing locally? Can we create documentations regarding coverage? What is the expected coverage?

**Comment by jennylia** [comment]
@BondAnthony Would you be able to make me a contributor so I can make more commits to this repo? In regards to my recent file change regarding pug file for undefined checks, please see: https://github.com/pugjs/pug/issues/656

**Comment by jennylia** [comment]
#25 #19 #22 
I think this might took care of these... Please double check.

**Comment by jennylia** [comment]
Please accept this PR. 👍 
I have included the logs and some emojis cuz I like emojis
:sparkling_heart:
:high_heel:
:lipstick:

Server running at http://Jennys-MacBook-Air.local:3000/
  Testing express server
    ✓ Responds to / (44ms)
    ✓ Returns 404 for everything else
    ✓ Returns empty array for api/status (561ms)
    ✓ Returns empty array if no service added (140ms)
    ✓ Returns 404 if posting service without serviceName (39ms)
    ✓ Returns 404 if posting service without value
    ✓ Returns true service when deleting it by id (68ms)
    ✓ Returns 404 if deleting service without id (59ms)

  Testing HTML response
    ✓ Checking HTML responses (39ms)
    ✓ Checking hostName endpoint

  Testing post endpoints response
    ✓ Checking successful post requests, online
    ✓ Checking successful post requests, offline


  12 passing (1s)

=============================================================================
Writing coverage object [/Users/jennylian/Desktop/play/hacktoberfest/status-service/coverage/coverage.json]
Writing coverage reports at [/Users/jennylian/Desktop/play/hacktoberfest/status-service/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 87.5% ( 42/48 )
Branches     : 84.62% ( 11/13 )
Functions    : 77.78% ( 7/9 )
Lines        : 87.5% ( 42/48 )
================================================================================

**Comment by BondAnthony** [comment]
@jennylia these commits look good and it looks like you figured out how to generate the coverage locally. Thank you for support and I've added you as a contributor to the project.

**Pull request merged**
