### PR TITLE
[WIP] Setup docker container with PostgreSQL as indipendent datastore

### PR DESCRIPTION
**Pull request by nickgnd**
related to #26 

- setup docker container with PostgreSQL
- add basic documentation to README

Please, give me some inputs to improve this PR and fit the requirements.

### CODE REVIEW

**Comment by BondAnthony** [comment]
@nickgnd what about using mongodb? Using mongo would allow for easy use of mongoose in the backend services. @jennylia thoughts on a datastore, I've only used mongo with nodejs. Relational side I can do about anything.

**Comment by nickgnd** [comment]
Hi @BondAnthony. Yeah, the DB choice depends on the requirements of the project.
You can set up easily also Postgres with [sequelize.js](http://docs.sequelizejs.com/en/v3/), but if you and the dev team know well mongo, this is for sure the better choice.

I can send you a PR with a new container in the next days :)

**Comment by BondAnthony** [comment]
Hey @nickgnd let's revise this pull request off of master but leave this one open. I'd like to look into sequelize and run a few tests. Please open a new pull request for the mongodb solution on a new feature branch. I need to run a number of load tests on the app to determine the best solution.  If possible could you move the DB Docker content into a sub directory called database. I would like to keep this module as much as possible.

Thank you for the support again!

**Comment by nickgnd** [comment]
Hi @BondAnthony, ok! 

> let's revise this pull request off of master but leave this one open
If you create a new branch, I can close this PR and open a new one against the new branch. Let me know.

> Please open a new pull request for the mongodb solution on a new feature branch.
👍 

> If possible could you move the DB Docker content into a sub directory called database.
👍

**Comment by BondAnthony** [comment]
@nickgnd new branch created, feature/issue26

**Pull request closed without merging**
